server:
  port: 8080
spring:
  datasource:
      username: root
      password: root
      url: jdbc:mysql://39.106.13.15:3306/app?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.liuwjg.dao: debug


